name: Verify (dependabot)

on:
  pull_request_target:
    branches:
      - main

env:
  NODE_VERSION: 14.x

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Configure Package Manager
        run: |
          echo Configuring NPM_READ_TOKEN globally for .npmrc
          npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_READ_TOKEN }}
          npm whoami

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --coverage

      # TODO: Use code-coverage-action once upload: false is supported
      - name: Comment test coverage
        uses: raulanatol/jest-coverage-comment-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-existing-reports: true

      - name: Build
        run: yarn build
